Repository PawanJaiswal08/leetcode-solutions, pull requests merged in 2022-10, with the labels that each got.

#2 added solution - 95. Unique Binary Search Trees II
  95. Unique Binary Search Trees II.cpp
Labels: hacktoberfest-accepted

#4 30. Substring with Concatenation of All Words
  30.Substring-with-Concatenation-of-All-Words.cpp
Labels: hacktoberfest-accepted

#3 added 12. Integer to Roman
  12. Integer to Roman.cpp
Labels: hacktoberfest-accepted

#8 Create README.md
  README.md
Labels: hacktoberfest-accepted

#9 sqrt of a number
  69.sqrtx.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 Create sum_triangle.cpp
  sum_triangle.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#6 Add files via upload
  spiralMatrix.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#11 added 7-reverse-integer
  7.reverseInteger.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#10 XOR Encryption by Shifting Plaintext
  hack.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 Added 48. Rotate Image
  48.RotateImage.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Added Banker's Algorithm
  BANKERS-ALGO.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 lc_11_sol
  11.contain-most-water.py
  19.remove-nth-from-end-of-list.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#22 Added Sieve of Eratosthenes code in Java
  Sieve of Eratosthenes.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 Added
  josh-solution.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 Added Next permutation
  Next-Perm
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#23 push-dominoes
  push-dominoes.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#21 Create 39. Combination Sum
  39. Combination Sum
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#20 Create 11. Container With Most Water
  11. Container With Most Water
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 added 9 solution files java hactoberfest-2022
  1.Two-sum.java
  12.Integer to Roman.java
  2.Add-Two-Numbers.java
  3.Longest_Substring.java
  4.Median_of_two_Sorted_array.java
  5.Longest_Palindrome_Substring.java
  7.Reverse.java
  8.String_to_Integer.java
  9.Palindrome-Number.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 Added 268.Missing_Number.java
  268.Missing_Number.java
  832.Flipping_an_Image.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 Create 2149. rearrange array elements by sign.cpp
  2149. rearrange array elements by sign.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#32 maximal square
  maximal square.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#30 Sanketr113
  CircularDoubleLinkedList.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#29 Create 53. Maximum Subarray
  53. Maximum Subarray
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#31 Pranjal singh
  singly linked list
  singly_linked_list
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Create 132-pattern.cpp
  132-pattern.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Create 61. Rotate List
  61. Rotate List
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#27 Create code.cpp
  567. Permutation in String/code.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#34 Create PeakIndexinaMountainArray.cpp
  PeakIndexinaMountainArray.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#33 112. PathSum.cpp
  112. PathSum.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#49 path_sum.java
  112. Path sum
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#48 Create Peak Index of an Mountain Array.cpp
  Peak Index of an Mountain Array.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#47 Create level_order_tree_traversal.cpp
  level_order_tree_traversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#46 Richest Customer Wealth
  richest-wealth.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#45 659. Split Array into Consecutive Subsequences
  659-split-array-into-consecutive-subsequences/659-split-array-into-consecutive-subsequences.cpp
  659-split-array-into-consecutive-subsequences/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 994. Rotting_Oranges.cpp
  994. Rotting_Oranges.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 Added combinational sum leetcode sol.
  CombinationSum.java
  WordSearch.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#39 Create Minimum time taken to BURN the Binary Tree from a Node
  All Nodes Distance K in Binary Tree
  Minimum time taken to BURN the Binary Tree from a Node
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#41 Create Remove Linked List Elements
  Remove Linked List Elements
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#42 added solution for 37.Sudoku Solver.cpp
  37.Sudoku Solver.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#40 PigLatin in Python
  PigLatin in Python
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#53 Add Stacks
  stacks.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#51 mirror reflection
  Mirror Reflection.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#50 Added Search Insert Position solution
  Search-Insert-Position.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#54 leetcode number of 1 bits problem
  number_of_1_bits.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#60 392.is-subsequence.cpp
  392.is-subsequence.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#61 1823.find-the-winner-of-the-circular-game.cpp
  1823.find-the-winner-of-the-circular-game.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#62 238.odd-even-linked-list.cpp
  238.odd-even-linked-list.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#79 Added Three Dice Problem
  threedice.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#64 278. First Bad Version
  278. First Bad Version.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#55 check number has equal digit count digit and value
  check number has equal digit count digit and value
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#83 Added medium level leetcode problem
  SudokuSolver.java
  TargetSum.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#85 Added 264 Ugly Number II
  264-Ugly-Number-II.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#84 334. Increasing Triplet Subsequence.cpp in O(n)
  334. Increasing Triplet Subsequence.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#81 Create MergetwosortedArray.cpp
  MergetwosortedArray.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#78 990. Satisfiability of Equality Equations
  Satisfiability_of_Equality_Equations.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#77 13. Roman to Integer
  RomanToInteger
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#76 622. Design Circular Queue
  MyCircularQueue.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#63 Solution for AP Problem in Leetcode
  arithmeticProgression.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#88 This is my project please accept or else .....
  test29.c
  test30.c
  test31.c
  test32.c
  test33.c
  test34.c
  test35.c
  test36.c
  test37.c
  test38.c
  test39.c
  test40.c
  test41.c
Labels: invalid

#95 double linked list
  double_linked_list_example.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#92 Create Create Maximum Subarray
  Create Maximum Subarray
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#91 Create Two Sum.cpp
  Two Sum.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#90 2212.Maximum Points in an archery competition
  maximum_points_in_archery.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#89 Added a program for contribution
  array_rotate.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#87 Leetcode questions
  3SumClosest.cpp
  Add two nos.cpp
  CombinationSumII.cpp
  KMP.cpp
  Merge_two_sorted_list.cpp
  Number_of_Islands.cpp
  SelectionSort.cpp
  longest cycle in graph.cpp
  reverse integers.cpp
  two sum.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#75 added solution for 33.Search in Rotated Sorted Array.cpp
  300.Longest Increasing Subsequence.cpp
  33.Search in Rotated Sorted Array.cpp
  46.Permutations.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#59 Valid_Parenthesis_String.java
  Valid Parenthesis String
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#96 Create Detect and Remove Cycle
  Detect and Remove Cycle
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#69 75. Sort Colors - Java
  75-Sort-Colors.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#66 3Sum_Closest.java
  16. 3Sum Closest
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#67 Create 653. Two Sum IV - Input is a BST.java
  653. Two Sum IV - Input is a BST.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#68 59. Spiral Matrix II
  59.Spiral-Matrix-II.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#58 Add questions 876,56 leetcode
  .vscode/settings.json
  56-merge-intervals.cpp
  876-middle-of-linkedlist.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#57 Create cpp solution
  202 HappyNumber.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#65 Create 1812. Determine Color of a Chessboard Square
  1812. Determine Color of a Chessboard Square
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#56 Added Code to find prime factors
  prime_factor.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#101 Added Solution of Rotate Image in java
  48.Rotate Image.java
  two sum.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#100 solution for longest palindromic subsequence
  longest-palindromic-subsequence.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#99 add valid sudoku cpp solution
  validSudoku.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#98 Create simple_sieve.cpp
  simple_sieve.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#97 Create firstAndLastposnofElementinSortedArray.cpp
  firstAndLastposnofElementinSortedArray.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#105 Create mergeTwoLists.c
  mergeTwoLists.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#102 Added CPP code of swap nodes in pairs
  24.swap nodes in pairs.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#104 Added leetcode Solutions
  QuickSort.py
  README.md
  palindromeCheck.py
  perform the binary search.py
  perform the linear search.py
  qrcode.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#103 Update 264-Ugly-Number-II.cpp
  264-Ugly-Number-II.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#114 added FactorialTrailingZeroes.java
  FactorialTrailingZeroes.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#113 Create Two Sum
  Best time to buy and Sell Stock
  Two Sum
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#112 Roman_to_Integer.java
  13. Roman to Integer
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#111 Check_if_the_Sentence_Is_Pangram.java
  1832. Check if the Sentence Is Pangram
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#110 Added Solution of N queen in cpp
  51.N Queen.cpp
  71.Simplify Path.cpp
  81.Search in a rotated sorted array II.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#109 Create FriendCircles.java
  FriendCircles.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#107 Create UniquePaths.py
  UniquePaths.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#106 Create FindFandLPositionofElementinSortedArray.py
  FindFirstandLastPositionofElementinSortedArray.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#135 Create Candy.cpp
  Candy.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#134 Create Best Time to Buy and Sell Stock
  Best Time to Buy and Sell Stock
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#132 Create Interleaving String.cpp
  Interleaving String.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#131 Create Median of Two Sorted Arrays.cpp
  Median of Two Sorted Arrays.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#130 Create Isomorphic String.cpp
  Isomorphic String.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#127 49. Group Anagrams
  49.Group-Anagrams.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
